### ISSUE TITLE
Allow settings PCDs in environment

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#171]
**Is your feature request related to a problem? Please describe.**
Currently, this is what you need to do to add the --pcd flag to the build command.
```python
pcds = " --pcd gSiPkgTokenSpaceGuid.PcdCpuEnable=TRUE"
pcds += " --pcd gSiPkgTokenSpaceGuid.PcdPchEnable=TRUE"
self.env.SetValue("BLD_*_DUMMY_PCDS", "DUMMY" + pcds, "Platorm HardcodedHack") 
```

Doesn't look great huh? 

**Describe the solution you'd like**
Maybe something like:
``` python
self.env.SetPcdValue("gSiPkgTokenSpaceGuid.PcdCpuEnable", TRUE);
```

**Describe alternatives you've considered**

**Additional context**

**Comment by spbrogan** [comment]
I think my real question is should we be configuring PCDs this way?  Is PCDs the right tool for this.  Configuration is great until it gets too much.  by opening up PCDs we just opened up 100s or 1000s of configuration options.  PyTools has tried to stay one layer above this.  Not saying it is wrong....just things to think about.

**Comment by matthewfcarlson** [comment]
So I agree with you. Allowing users to specifically set pcds leads to a precedent. But I think there's an underlying need to be able to pass additional arguments to edk2 build. For example, I was diagnosing some issue and needed verbose turned on. Currently your only choices are to modify uefi builder in pytool or use the hack I posted above

**Comment by spbrogan** [comment]
Much of this is on purpose.  Since we want the whole build system to align if we just allow a transparent passthru we don't get alignment for the whole build system.  For example if you want verbose I think it should verbose for the whole build not just the edk2 part of the build.  

As for PCDs I think we should figure out how to manage and align settings.  PCDs is just one method to get configuration into edk2 build and edk2 fw modules.
