### ISSUE TITLE
Support to handle multiple edk2 builds in one build process

### ISSUE THREAD

**Issue by BobCF** [tianocore/edk2-pytool-extensions#177]
**Is your feature request related to a problem? Please describe.**
In the entire Intel platform build process, there are multiple edk2 builds, build a specific module, build FSP from source, build BIOS, build final firmware binary image. 

How can Pytools support to handle multiple edk2 builds in one build process?

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by spbrogan** [comment]
stuart_build isn't optimized for this.  There are ways to do it and @matthewfcarlson can provide some examples but if this is an important enough/common use case maybe a new stuart invokable could be created designed for this.  Invokables have a class hierarchy so that they can easily support lightweight customization.

**Comment by matthewfcarlson** [comment]
There's a document here: https://github.com/tianocore/edk2-pytool-extensions/blob/master/docs/usability/creating_invocable.md that's a tutorial of how to write the invokable I wrote for binary builds. You should be able to adapt it pretty readily to do what you want. I'm also happy to help and provide more concrete guidance by email or teams if that's easier.
