### ISSUE TITLE
CLI flag to enable all python output to the console for easier debug

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#182]
**Is your feature request related to a problem? Please describe.**

When trying to debug an issue on a remove server it would be helpful is all filtering could be disabled and all output written to the console

**Comment by Javagedes** [comment]
@spbrogan This seems a bit like an overstep on internal stuart because the platform can set and read the command line option for this since parsing the command line already occurs before setting the logging level

PlatformBuild.py
``` py
...
def AddCommandLineOptions(self, parserObj):
    parserObj.add_argument('-d', '--debug', dest='debug_output', action='store_true', default=False)

def RetrieveCommandLineOptions(self, args):
    self.debug_output = args.debug_output

def GetLoggingLevel(self, loggerType):
    if self.debug_output:
        return logging.DEBUG
    return logging.INFO
...
```

If I were to implement this internally, I would do almost exactly this, but within `edk2_invocable.py`

**Comment by Javagedes** [comment]
I can enable this by checking for the environment variables DEBUG (for azure-pipelines) and RUNNER_DEBUG (github action) being set to true. DEBUG is a default env variable in azure pipelines that users can set to true. RUNNER_DEBUG is automatically set to true when you click "enable debug logging" when re-running an action
