### ISSUE TITLE
Common way of expressing DSC path in ci settings yaml

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#197]
**Is your feature request related to a problem? Please describe.**
Currently you need to specify the DSC to each plugin that requests it. While it might be desirable to be able to override the DSC path for a specific plugin, it would be nice to specify the DSC for a package in just one place

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by spbrogan** [comment]
need to understand your pain point.  I don't see the value given that 2 different DSCs are only listed twice.  I also prefer less entanglement of plugins so I don't think i like this idea.  If there was a concept of a template token..and then the plugin config would use token replacement....this would get you the benefits of not having the path multiple times but still per plugin config.  

Otherwise i vote "wont fix"

**Comment by matthewfcarlson** [comment]
So I was working on a ECC based linter plugin and found myself defining where the DSC was in every ci settings yaml. So it would be specified for each plugin that wanted to know where the DSC was. In most packages, the DSC would be specified three times

**Comment by spbrogan** [comment]
true but I think forcing explicit DSC path per plugin rather than some assumed path or heuristic or common config that multiple plugin's depend on is better.  Given that i suggest we close as won't fix at this time.   If YAML supported some sort of reference notation that allowed the yaml to declare a dsc path and then use that reference for the different plugins i think that would be the best of both worlds.

**Comment by matthewfcarlson** [comment]
I don't like it but I agree with your assessment
