### ISSUE TITLE
Dinstinguish edk2 workspace directory from working directory

### ISSUE THREAD

**Issue by PierreARM** [tianocore/edk2-pytool-extensions#237]
Hello,
I am currently looking at enabling a CI for the edk2-platforms repository.

There is a strong dependency of the edk2-platforms repository over the edk2 repository:
 - most platforms require packages available in the edk2 repository
 - the python plugins in 'edk2/.pytool/Plugin' can be re-used 
 - env variables like 'WORKSPACE' and 'EDK_TOOLS_PATH' must point to folders or files that can be re-used from edk2 [1]
Cf [1], when implementing a .pytool/CISettings.py for edk2-platforms, the GetWorkspaceRoot() method must point to the 'edk2' repository.

The issue I face is that there is currently no distinction between the location of the location of the edk2 repository (obtained through GetWorkspaceRoot()) and the location where to run the tests.
For instance, in invocables/edk2_setup.py:class Edk2PlatformSetup: def Go() (and maybe in other places), the git commands are executed for the repo from GetWorkspaceRoot() (i.e. edk2), but I would need to execute them for the edk2-platforms repository.

One way to solve this would be to implement another interface (GetWorkingDir() for instance). This method would return GetWorkspaceRoot() when not implemented. This would allow to run edk2 tests on any repository.

[1] https://edk2-docs.gitbook.io/edk-ii-build-specification/6_quick_start/61_environment_variables
WORKSPACE: 'This variable points to a directory that will contain a Conf directory'
EDK_TOOLS_PATH: 'The EDK_TOOLS_PATH variable must point to the directory containing the BaseTools/Conf directory'

**Comment by spbrogan** [comment]
Not sure i totally follow the issue here.  I have definitely used the ci plugins from edk2 repo in a multi-repo solution.  

My first question is why is the edk2 repo declared the workspace root.  The workspace root should be the root of the workspace being tested. If you are testing or building packages that are not in edk2 then edk2 should not be your workspace root.   Your build environment should be making use of packages path to control the locations of other packages/dependencies.  The conf folder will definitely be created in your workspace root but that will be created during the edk2 build operation based on the template files in the basetools.  

I recently opened a few bugzillas on edk2-platforms repo because the code there has hardcoded file path assumptions that break numerous things and don't fully leverage the capabilities of edk2 build tools.  

https://bugzilla.tianocore.org/show_bug.cgi?id=3259
https://bugzilla.tianocore.org/show_bug.cgi?id=3264

We have a bunch of examples of repos that have mu_basecore (very similar to edk2 repo) as a dependency but don't declare it as the workspace root.
https://github.com/microsoft/mu_plus
https://github.com/microsoft/mu_tiano_platforms

I have also setup a build of some of the edk2-platforms platforms to do ci and didn't have any path issue but I agree the way edk2-platforms is setup makes it really hard to do CI well especially given it doesn't track it dependencies but that is a discussion for the edk2-platforms list.

**Comment by PierreARM** [comment]
Hi,
The reasons I wanted to have a mean to distinguish the edk2 repo and the repo the tests are performed on (here edk2-platforms) are:

1. For what it's worth, the WORKSPACE env variable is asked to point to the edk2 repo [1], which is not the case for the mu_tiano_platforms repo [2]
2. The Ecc CI test [3] makes some static analysis on the 'git diff' between the master branch and the tested branch of the tested repo (here edk2-platforms). The Ecc config file is available and fetched from the edk2 repo [4]. The 'git diff' is currently done on the edk2 repo [5] when it should be done on the tested repo.
This is where the need of making a distinction between edk2 and the tested repo comes.
The Ecc test seems to be disabled for the mu_basecore repo [6], so it must be ok for this repo.

Thanks for the links to the bugzillas.

[1] https://edk2-docs.gitbook.io/edk-ii-build-specification/6_quick_start/61_environment_variables#6-1-1-required-environment-variables
[2] https://github.com/microsoft/mu_tiano_platforms/blob/release/202102/.pytool/CISettings.py#L175
[3] https://github.com/PierreARM/edk2/blob/master/.pytool/Plugin/EccCheck/EccCheck.py
[4] https://github.com/PierreARM/edk2/blob/master/.pytool/Plugin/EccCheck/EccCheck.py#L182
[5] https://github.com/PierreARM/edk2/blob/master/.pytool/Plugin/EccCheck/EccCheck.py#L72
[6] https://github.com/microsoft/mu_basecore/blob/release/202102/.pytool/Plugin/EccCheck/EccCheck_plug_in.yaml#L8

**Comment by spbrogan** [comment]
I don't agree with your interpretation of **workspace**.  Reading that it just says workspace will be where `conf` and `build` directories go.  There are many ways to configure your workspace and the edk2 basetools are really a build system for edk2 style packages.  Not just the edk2 repository and thus you could use edk2 basetools to build code without edk2 without any issue.  The example given in the doc is for the edk2 repo but that to me is out of convenience.  

Ecc CI plugin has a lot of issues.  Many are already documented in bugzillas.  But if you setup your workspace as the repo you are testing (doing ci on) then it should work fine.  We don't run ECC plugin in MU because it destroys your local changes without warning and we find that more problematic than helpful.   Hopefully that will get fixed and then ECC and code formatting can be enabled in edk2 and MU.

**Comment by spbrogan** [comment]
Another comment on the 'git diff'.  If your repo is configured to track your dependencies (using submodules or some sort of "manifest") then you generally ignore those directories and thus the ECC plugin will also ignore them because they will not be in the diff.  To me, that (tracking dependencies and fixing mixed ownership) is the first thing edk2-platforms needs to solve.

**Comment by PierreARM** [comment]
Hi,
I agree with you on all the points.
It seems that I could have just fetched the config files Ecc requires [1] via the EDK_TOOLS_PATH variable. Like this the workspace directory can point to the tested repository.

I am closing the conversation since a solution is available.
Thanks

[1] BaseTools/Source/Python/Ecc/config.ini and BaseTools/Source/Python/Ecc/exception.xml
