### ISSUE TITLE
Unit test will not run on the single module build

### ISSUE THREAD

**Issue by kuqin12** [tianocore/edk2-pytool-extensions#306]
**Describe the bug**
When the user specifies to build and execute a single unit test by issuing `BUILDMODULE=**.inf` (as documented in [edk2](https://github.com/tianocore/edk2/blob/master/UnitTestFrameworkPkg/ReadMe.md#iterating-on-a-single-test)), the actual unit test will not end up being executed.

This is because the "BUILDMODULE" flag will disable the post build plugins from running [here](https://github.com/tianocore/edk2-pytool-extensions/blob/61133aca78eeab1edb2f24024ffd3906682fd556/edk2toolext/environment/uefi_build.py#L257) and unit tests are executed as part of post build plugins: https://github.com/tianocore/edk2/blob/master/BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py#L30.

**To Reproduce**
1. Use any package that supports unit test dsc.
2. Issue the "NOOPT" target and "BUILDMODULE" to specify a single module.
3. Notice that the unit test not being run.

**Expected behavior**
The single unit test will run.

**Execution environment**
Windows.

**Comment by Javagedes** [comment]
@kuqin12 The reason we disable post build plugins from running is that we "promise" plugins that the entire project is built. By setting BUILDMODULE, we are no longer building the entire project, which may cause some plugins (that expect an entire build project) to fail. Due to this, we disable all post build plugins.

My suggestion here is to edit the HostUnitTestCompilerPlugin to run the plugin itself if BUILDMODULE is set. `ICiBuildPlugin`s already have all the information needed to do this.

Starting at https://github.com/microsoft/mu_basecore/blob/877f781ada3b2b56c7397d02f30dae798f9ab5d9/.pytool/Plugin/HostUnitTestCompilerPlugin/HostUnitTestCompilerPlugin.py#L146

You can add the following code. I've already verified in successfully executes host based tests and also catches any host based test failures similar to if running all host based tests.

```python
# Run the tests manually if only building a single module, as it will be skipped by stuart_ci_build
mod = environment.GetValue("BUILDMODULE")
if (mod is not None and len(mod.strip()) > 0):
    for plugin in PLM.GetPluginsOfClass(IUefiBuildPlugin):
        if plugin.descriptor['scope'] == 'host-based-test':
            if plugin.Obj.do_post_build(uefiBuilder) != 0:
                tc.SetFailed("Compile failed for {0}".format(packagename), "Compile_FAILED")
                tc.LogStdError("{0} Compile failed with error code {1} ".format(AP_Path, ret))
                return 1
```

If @kuqin12 and @spbrogan are okay with it, I can put up a PR in MU_BASECORE with the change.

**Comment by Javagedes** [comment]
Resolved in MU_BASECORE via https://github.com/microsoft/mu_basecore/pull/219
