### ISSUE TITLE
git operations standardized for ci_setup and platform_setup

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#43]

**Comment by Javagedes** [comment]
Working on this. 

Here is the current situation:
| **File**                                        | **Relies on**                                     |
|------------------------------------|----------------------------------------|
| edk2_git.py                                 | N/A - Basis of repo functionality      |
| repo_resolver.py                         | edk2_git.py                                       |
| self_describing_environment.py | PyGit2                                               |
| git_dependency.py                     | repo_resolver.py                               |
| edk2_ci_setup.py                        | repo_resolver.py                               |
| edk2_setup.py                            | Uses raw RunCmd git commands    |


Here is the end state plan:
| **File**`                      | **Relies on**                     | **Changes**                                  |
|--------------------------------|-----------------------------------|----------------------------------------------|
| edk2_git.py                    | N/A - Basis of repo functionality | Use PyGit2 as basis of Repo management       |
| edk2_git_resolver.py           | edk2_git.py                       | repo_resolver + submodule resolve capability |
| self_describing_environment.py | edk2_git.py                       | Use edk2_git for worktrees                   |
| git_dependency.py              | edk2_git_resolver.py              | `resolve()` -> `resolve_repo()`              |
| edk2_ci_setup.py               | edk2_git_resolver.py              | `resolve_submodule_all()`                    |
| edk2_setup.py                  | edk2_git_resolver.py              | `resolve_all()` -> `resolve_repo_all()`      |

Main issues
* edk2_git.py Repo() is currently static. No values change once the class is created, regardless of if the physical repo changes. Additionally, it uses way more "RunCmd"s then necessary, as PyGit2 can quickly read the git database rather than run git commands themselves. edk2_git will be updated to rely on PyGit2 where possible to reduce the amount of RunCmd's used. As a side effect, it allows attributes to change depending on repo state (As an example, if say a file is updated, repo.dirty will be updated also).
* edk2_git_resolver.py (changed from repo_resolver) currently provides a few functions to ensure a repo meets the dependency requirements. I plan on adding new functions to do the same but based off the submodule requirements of the base repo. I.e. `resolve()` -> `resolve_repo()` and add a new `resolve_submodule()` function
* self_describing_environmept.py uses raw PyGit2 for discovering subtrees. This will simply be abstracted away behind edk2_git.py
* git_dependency.py only needs API changes based on edk2_git_resolver.py
* edk2_ci_setup.py only needs API changes based on edk2_git_resolver.py
* edk2_setup.py's core logic will be used as the basis for `resolve_submodule()`, using edk2_git.py Repo commands rather than RunCmd and edk2_setup.py will just need to call `resolve_submodule()` or `resolve_submodule_all()`
