### ISSUE TITLE
[Bug]: Calling platform build name --help starts a build

### ISSUE THREAD

**Issue by makubacki** [tianocore/edk2-pytool-extensions#708]
### Describe the Bug

With edk2-pytool-extensions 0.26.3 calling `python Platforms/QemuQ35Pkg/PlatformBuild.py` results in a build being started instead of printing help.

### What Python version are you using?

Python 3.12

### Reproduction steps

- Install Python 3.12
- Install edk2-pytool-extensions 0.26.3
- Clone mu_tiano_platforms and set up the workspace
- Call `python Platform/QemuQ35Pkg/PlatformBuild.py --help`
  - A build is started instead of printing help text

---

Reverting commit https://github.com/tianocore/edk2-pytool-extensions/commit/dc5b3cdf66e860b55c34b2ca5cc6320c7f776b8f locally restores previous behavior.

### Expected behavior

Print help text when `--help` is given.

### Pip packages

edk2-pytool-extensions 0.26.3
edk2-pytool-library    0.19.7

**Comment by Javagedes** [comment]
Thanks for bringing this to my attention. This is because there are two rounds of parsers. The first round is to find the build module use it to gather it's command line arguments. The second round of parsing is to parse for those command line arguments and then execute.

In the situation where the build module is provided, the first round of parsing consumes the --help argument, so when the second round of parsing occurs, the help flag does not exist and print help is not triggered. 

PR #714 adds back in the "--help" flag to sys.argv if it was detected in the first round of parsing.
